### ISSUE TITLE
Socket.io port hardcoded to 80

### ISSUE THREAD

**Issue by fishfree** [uts-cic/acawriter#107]
I changed the Nginx port mapping in the docker-compose .yml:
```
...  
nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        network_mode: bridge
    # Enable for local development
    # volumes:
    #   - ./public/css:/var/www/css
    #   - ./public/js:/var/www/js
    restart: unless-stopped
    ports:
      **- "8009:80"**
    networks:
      - app-network
      - socket-network
...
```
However, when I click on "Get Feedback" button, the browser console shows errors as below:
![image](https://github.com/uts-cic/acawriter/assets/1741341/a6b968e4-2113-4d70-9a8e-e9b8d78aafe6)

I think it should respect the port mapping in the docker-compose.yml. Or do you know in which container to manually modify the related code, please?
